/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        ElInput: typeof import('element-plus/es')['ElInput']
        Footer: typeof import('./components/Footer.vue')['default']
        Header: typeof import('./components/Header.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        Sidebar: typeof import('./components/Sidebar.vue')['default']
        ToolCard: typeof import('./components/ToolCard.vue')['default']
    }
}
